on:
  schedule:
    - cron: '*/1 * * * *'
jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: say hello world
        run: echo "the current server time is $(date)"
      - name: not on monday
        if: github.event.schedule != '*/5 * * * *'
        run: echo "skip this run"
      - name: every 5 mins
        run: echo "run every 5 mins"
